### ISSUE TITLE
The order confirmation email was not sent

### ISSUE THREAD

**Issue by ojosarp** [Midtrans/SNAP-Magento2#4]
new order email was not send after install this module, pls. help

**Comment by carolus10benny** [comment]
For "Notification Email" from Midtrans triggering according to data entered into the MAP or Midtrans Dashboard system. In Magento there is also a "core" module that handles related to order email notifications. Please email to "support@midtrans.com" related to the problem you are experiencing, because this plugin module does not conflict with the email notification module that Magento has.
